
//////////////////////////////////////////////////////////////////////////
// Autogenerated 2020-06-25 23:40:21.390                                //
// ANY CHANGES TO THIS DOCUMENT WILL BE LOST UPON RE-GENERATION         //
//////////////////////////////////////////////////////////////////////////

using System.Reflection;
using System;

[assembly: AssemblyVersion("0.5.632.20177")]
[assembly: AssemblyFileVersion("0.5.632.20177")]
[assembly: AssemblyInformationalVersion("2d7bbdd857dcf63b0232e94410b5dad8df826bef")]
[assembly: AssemblyCompany("Unknown6656")]
[assembly: AssemblyCopyright("Copyright © 2018 - 2020, Unknown6656")]
[assembly: AssemblyProduct("AutoIt3 Interpreter by Unknown6656")]
[assembly: AssemblyTitle("autoit3")]

public static class __module__
{
    public static string Author { get; } = "Unknown6656";
    public static string Year { get; } = "2018 - 2020";
    public static string Copyright { get; } = "Copyright © 2018 - 2020, Unknown6656";
    public static Version? InterpreterVersion { get; } = Version.Parse("0.5.632.20177");
    public static string GitHash { get; } = "2d7bbdd857dcf63b0232e94410b5dad8df826bef";
}
