
//////////////////////////////////////////////////////////////////////////
// Autogenerated 2020-06-07 21:36:10.793                                //
// ANY CHANGES TO THIS DOCUMENT WILL BE LOST UPON RE-GENERATION         //
//////////////////////////////////////////////////////////////////////////

using System.Reflection;
using System;

[assembly: AssemblyVersion("0.0.216.20159")]
[assembly: AssemblyFileVersion("0.0.216.20159")]
[assembly: AssemblyInformationalVersion("6145e07374d2b52f9a78fa2b5ae6fc138991e4c4")]
[assembly: AssemblyCompany("Unknown6656")]
[assembly: AssemblyCopyright("Copyright © 2018 - 2020, Unknown6656")]
[assembly: AssemblyProduct("AutoIt3 Interpreter by Unknown6656")]
[assembly: AssemblyTitle("autoit3")]

public static class __module__
{
    public static string Author { get; } = "Unknown6656";
    public static string Year { get; } = "2018 - 2020";
    public static string Copyright { get; } = "Copyright © 2018 - 2020, Unknown6656";
    public static Version? InterpreterVersion { get; } = Version.Parse("0.0.216.20159");
    public static string GitHash { get; } = "6145e07374d2b52f9a78fa2b5ae6fc138991e4c4";
}
