
//////////////////////////////////////////////////////////////////////////
// Autogenerated 2020-06-23 11:49:31.163                                //
// ANY CHANGES TO THIS DOCUMENT WILL BE LOST UPON RE-GENERATION         //
//////////////////////////////////////////////////////////////////////////

using System.Reflection;
using System;

[assembly: AssemblyVersion("0.5.608.20175")]
[assembly: AssemblyFileVersion("0.5.608.20175")]
[assembly: AssemblyInformationalVersion("e627ec984171754f513fb6b7c3dbc48d2abfca0d")]
[assembly: AssemblyCompany("Unknown6656")]
[assembly: AssemblyCopyright("Copyright © 2018 - 2020, Unknown6656")]
[assembly: AssemblyProduct("AutoIt3 Interpreter by Unknown6656")]
[assembly: AssemblyTitle("autoit3")]

public static class __module__
{
    public static string Author { get; } = "Unknown6656";
    public static string Year { get; } = "2018 - 2020";
    public static string Copyright { get; } = "Copyright © 2018 - 2020, Unknown6656";
    public static Version? InterpreterVersion { get; } = Version.Parse("0.5.608.20175");
    public static string GitHash { get; } = "e627ec984171754f513fb6b7c3dbc48d2abfca0d";
}
